language: php

sudo: false
dist: trusty

git:
  depth: 3

notifications:
  email: false
  slack:
    secure: qKhDgvUA5A1PuIFx+QUEa8r4lqVX8BjWts/J5LBJ2QxtkFrpZ1v3iFH1jbjmyzAnk19YKE048iHbWUMKaVnb5UF9Ban/Qo/+/J4mB3TNj48YRZ+EpqQFwbzBEhbVOy199Kofk6p5gowdtC08xe/Ys9/WV7jZzYQrCmbDfQjI9FSrOQGgBVPUW2tOnB3wN7h1DaQtNqfz1UjyDXFmqrFTcVB8lSKzh5Rq5klB2nAzxYZCP0aMAh4EZpKEEggGKQwxsEJ3P/z8cj6SdxcwHqAslR/qCgpkCwoQ4V5jnGWn2C3k4gT7ReBC+RMy1U9iFPi+ak91LZWjINtJIKSIuS9j4TIMutpXkUNER5u/aavJAIw5UpBUQROIVa7YPxyK2PziB/vVBqnhO1ZoAv6W1IPnSAbVJ+3SXiAKkQvDe+Kqave5nRAfq5VNpT3RNpZSzusrPJNEtmbFtHWsa3pRGeFgVBmmAHfDGj0XbiphJpGibRLGJv4/cWSdj/oao02E8mxbazsPN/14+DgL13PXRj6G3GRWF3ncmXjDriUMprfWRchDYfjMw3OatUVx45Io/6HXdpn1aiQu1/WBSCIpFS420bXdP7fSWQXAh1pUNzvfo9qG9BtqEGn612CGn/UBHkN6+JNyMnb1Djhu+ckztZ1SINT1IUInbXpPbEkwIHbB8Qg=

branches:
  only:
    - master
    - "/^v[0-9\\.]+/"

cache:
  yarn: true
  directories:
    - "${HOME}/.composer/cache"
    - node_modules

stages:
  - name: check
    if: branch = master and tag IS blank and type IN (pull_request, api, cron)

before_script:
  - git clone --depth=1 https://github.com/wp-content-framework/travis-ci.git travis-ci
  - bash travis-ci/bin/prepare.sh

jobs:
  fast_finish: true
  include:
    - stage: check
      language: php
      php: '7.2'
      script: bash travis-ci/bin/php/phpcs.sh
    - stage: check
      language: php
      php: '7.2'
      script: bash travis-ci/bin/php/phpmd.sh

    - stage: check
      language: node_js
      node_js: '11'
      dist: trusty
      script: bash travis-ci/bin/js/js-lint.sh
